#!/bin/bash
ROOT_FOLDER=${0%/*}
BIN_FOLDER=${ROOT_FOLDER}/bin
BUILD_FOLDER=${ROOT_FOLDER}/build/

rm -rf ${BUILD_FOLDER}
scons board=iot-lab_A8-M3 toolchain=armgcc oos_openwsn dagroot=0 debug=1 sensorlab=1
mv ${ROOT_FOLDER}/build/iot-lab_A8-M3_armgcc/projects/common/03oos_openwsn_prog ${BIN_FOLDER}/openwsn_router
rm -rf ${BUILD_FOLDER}
scons board=iot-lab_M3 toolchain=armgcc oos_openwsn dagroot=1 sensorlab=0 bootload=42 
cp ${ROOT_FOLDER}/build/iot-lab_M3_armgcc/projects/common/03oos_openwsn_prog ${BIN_FOLDER}/openwsn_dagroot
